name       : libmatroska
version    : 1.4.4
release    : 1
source     :
    - http://dl.matroska.org/downloads/libmatroska/libmatroska-1.4.4.tar.bz2 : d3efaa9f6d3964351a05bea0f848a8d5dc570e4791f179816ce9a93730296bd7
license    : LGPL-2.1
summary    : PLEASE FILL ME IN
description: |
    Matroska library
builddeps  :
    - pkgconfig(libebml)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
