name       : libmatroska
version    : 1.7.1
release    : 12
source     :
    - https://github.com/Matroska-Org/libmatroska/archive/release-1.7.1.tar.gz : 64763443947833e6c17f1f555f4bb0df6c9f91881810d9d5e0f0bad3622d308b
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : The extensible, open source, open standard Multimedia container
description: |
    Matroska aims to become THE standard of multimedia container formats. It was derived from a project called MCF, but differentiates from it significantly because it is based on EBML (Extensible Binary Meta Language), a binary derivative of XML. EBML enables the Matroska Development Team to gain significant advantages in terms of future format extensibility, without breaking file support in old parsers.
builddeps  :
    - pkgconfig(libebml)
setup      : |
    %cmake . -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
