name       : libmatroska
version    : 1.5.0
release    : 8
source     :
    - https://github.com/Matroska-Org/libmatroska/archive/release-1.5.0.tar.gz : 0c364f74a9c6f339ed994d9da492e31289c7860b96083aba3111c58956727cd9
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : The extensible, open source, open standard Multimedia container
description: |
    Matroska aims to become THE standard of multimedia container formats. It was derived from a project called MCF, but differentiates from it significantly because it is based on EBML (Extensible Binary Meta Language), a binary derivative of XML. EBML enables the Matroska Development Team to gain significant advantages in terms of future format extensibility, without breaking file support in old parsers.
builddeps  :
    - pkgconfig(libebml)
setup      : |
    %cmake . -DBUILD_SHARED_LIBS=ON
build      : |
    %make
install    : |
    %make_install
