name       : libmatroska
version    : 1.4.8
release    : 7
source     :
    - https://github.com/Matroska-Org/libmatroska/archive/release-1.4.8.tar.gz : f178ca7529053c8861bb39487433eb1d3b0ccf64c9796ecb84beefc27dec8c39
license    : LGPL-2.1-or-later
component  : multimedia.library
summary    : The extensible, open source, open standard Multimedia container
description: |
    Matroska aims to become THE standard of multimedia container formats. It was derived from a project called MCF, but differentiates from it significantly because it is based on EBML (Extensible Binary Meta Language), a binary derivative of XML. EBML enables the Matroska Development Team to gain significant advantages in terms of future format extensibility, without breaking file support in old parsers.
builddeps  :
    - pkgconfig(libebml)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install

